version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wmfs/gazetteer-blueprint"
    versions:
    - 1.30.1
    - 1.30.3
    - 1.30.4
    - 1.31.0
    - 1.31.1
    - 1.32.0
  - dependency-name: "@wmfs/tymly-pg-plugin"
    versions:
    - 1.239.0
    - 1.240.0
    - 1.244.0
    - 1.246.0
  registries:
  - npm-registry-registry-npmjs-org
